### ISSUE TITLE
not working on sketch Version 41 (35326)

### ISSUE THREAD

**Issue by mridumehta** [designedbydc/asset-export-for-ios-and-android#2]

**Comment by illustree** [comment]
please update guys ...

**Comment by nielsbastian** [comment]
Could you please update this plugin. This one was the best there is out there. No need to create slices etc, it was perfect but doesn't work anymore in Sketch 42. Thanks a lot! =)

**Comment by WinayakBongarge** [comment]
Please update the plugin. I have tried every other export plug in this one is the best ever.
Its stopped working after Sketch 41 update.

**Comment by designedbydc** [comment]
Fixed with the latest update. Please update using 'Sketch toolbox' or replace the plugin manually.
