### ISSUE TITLE
Ignore Artboard bg when exporting

### ISSUE THREAD

**Issue by illustree** [designedbydc/asset-export-for-ios-and-android#3]
I can hardly imagine a case where it would be needed to export the Artboards BG in the asset ... usually you need a transparent canvas. Would be great if you did it so that when exporting it would ignore the bg set for the artboard. Much appreciated!

**Comment by designedbydc** [comment]
For the time being **Select the Artboard** and **uncheck** the **Background color > 'Include in export'** option while exporting assets. Will try to update the plugin to work as desired regardless of the option selected, It might take some time though
